export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';

export const SUBMIT = 'SUBMIT';

export const DELETE_ITEM = 'DELETE_ITEM';

export const INIT_LIST_ACTION = 'INIT_LIST_ACTION';

export const GET_INIT_LIST = 'GET_INIT_LIST';

export const GET_INIT_LIST_ACTION = 'GET_INIT_LIST_ACTION';